modLoader="javafml"

loaderVersion="[2,]"

license="MIT"

issueTrackerURL="https://discord.gg/WsuFsGSegD"

[[mods]]
modId="artisan_machines"
version="${mod_version}"
displayName="${mod_name}"
displayURL="http://curseforge.com/minecraft/mc-mods/artisan-machines"
logoFile = "icon.png"
mod_authors="${mod_authors}"
description='''Artisan Machines straight out of your favorite farming-dating simulator'''

#[[mixins]]
#config="artisan.mixins.json"

#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

[[dependencies.artisan_machines]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.artisan_machines]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="AFTER"
side="BOTH"